### ISSUE TITLE
No styles included

### ISSUE THREAD

**Issue by JulioC** [akserg/ng2-toasty#13]
I can't find how to include the styles used by this component. The DOM elements get inserted correctly, but no CSS is injected.

**Comment by akserg** [comment]
Everything depends on module loader. Did you have a look at simple examples:
- with SystemJS in [ng2-systemjs-demo](https://github.com/akserg/ng2-systemjs-demo)
- with Webpack in [ng2-webpack-demo](https://github.com/akserg/ng2-webpack-demo)

**Comment by JulioC** [comment]
Thanks, that solved my issue.

Maybe you should put a note on the README about the fact that we need to import the CSS manually.

**Comment by akserg** [comment]
Ok, will do.

**Comment by belall-shaikh** [comment]
can you please mention that where we need to import the CSS.
I can't find any CSS link in the samples.

**Comment by akserg** [comment]
I have updated the README.
