### ISSUE TITLE
Global timeout not working

### ISSUE THREAD

**Issue by brianchance** [akserg/ng2-toasty#18]
The global timeout is not every used. Timeout only gets set if a truthy value is passed on the options and since it is truthy, the global never gets used. From toasty.service.ts
`if (toastyOptions.timeout) {
    toast.timeout = toastyOptions.timeout || this.config.timeout;
} else {
    toast.timeout = null;
}`

Maybe it should be...
`toast.timeout = toastyOptions.hasOwnProperty('timeout') ? toastyOptions.timeout : this.config.timeout;`

Anytime the caller passes a value, it is used. Allows a caller to pass null/0 and override the default (I prefer errors to stay until cleared, the rest can timeout). Can also set the default to null/0 to turn off.

**Comment by akserg** [comment]
Agree. Fixed in 1.7.2

**Comment by brianchance** [comment]
Anyway to get the update pushed to npm?

**Comment by akserg** [comment]
Sorry, something wrong happened with build on Travis. Available from 1.7.3

**Comment by akserg** [comment]
Is all sorted?

**Comment by brianchance** [comment]
Looks good. Thanks for getting that in so quick.
