### ISSUE TITLE
Update title and msg

### ISSUE THREAD

**Issue by mburger81** [akserg/ng2-toasty#2]
Hi,

is it possibile to update the message dynamically? Can you implemnt something like that?

I use an Rx.Observable and count 10 seconds and I have to update the test in the message box.

I do something like that and i would update the variable seconds!

```
newToast() {
        let seconds = 10;

        var toastOptions: ToastOptions = {
            title: 'Do something',
            msg: seconds + ' seconds',
            showClose: false
        };

        this.toastyService.wait(toastOptions);

        const source$ = Observable.interval(1000)
            .take(seconds);

         source$.subscribe(
             (count)  => console.log(count),
             (err)      => console.error('Error: ${err}'),
             ()         => this.toastyService.clearAll()
         );
    }
 }
```

thx
  Michael

**Comment by akserg** [comment]
Hi Michael.

That is a good idea. I will back next week from vacation and implement it.

**Comment by mburger81** [comment]
Do you think you can also implement an observable and emit an event, I try to explain better.

If I set the timeout to 5000, I would also set a parameter as "evrey: 500ms" , so every 500ms I can do something, for example change msg or change color.

The other option is, If I change in my component the input variable for mgs: your service will notice that and change the value.

So I have to to a presentation on monday or thuesday so I will check what I can do, I have to search a workaround for that problem.

How I can set the box on the right bottom?

thx
  Michael

**Comment by akserg** [comment]
Actually I can do whatever we can imagine. I like the idea. Can you split the new idea into another issue, so we have better tracking and don't mix it with this one.

About position - by default the toaster container will appear in bottom right corner, but you can define new configuration via another values of ToastyConfig class. Check this out:

``` javascript
export class ToastyConfig {
    // Maximum number of toasties to show at once
    limit:number = 5;
    // Whether to show the 'X' icon to close the toast
    showClose:boolean = true;
    // The window position where the toast pops up. Possible values
    // bottom-right, bottom-left, top-right, top-left, top-center, bottom-center
    position:string = 'bottom-right';
    // How long (in miliseconds) the toasty shows before it's removed. Set to false to disable.
    timeout:number = 5000;
    // What theme to use. Possible values:
    // default, material or bootstrap
    theme:string = 'default';
}
```

Just create another instance of ToastyConfig with DI and that's it. Check the demo [ng2-webpack-demo](https://github.com/akserg/ng2-webpack-demo)

**Comment by akserg** [comment]
Hi Michael,

I have good news for you. You can use current version of ng2-toasty without modification to update the title and message of each of individual toasts dynamically. Check the example on [README](https://github.com/akserg/ng2-webpack-demo/blob/master/README.md) page or get it from demo projects:
- [ng2-systemjs-demo](https://github.com/akserg/ng2-systemjs-demo)
- [ng2-webpack-demo](https://github.com/akserg/ng2-webpack-demo)

Online demo contains this example as well [here](https://akserg.github.io/ng2-toasty/)

**Comment by akserg** [comment]
I will close this issue as it is seams solved. If you think this is not true please reopen this one or create another one.

**Comment by mburger81** [comment]
@akserg sorry for my late answer, but I was very busy on other things to implement for other presentations. This week I surely will try this!! =)

In meantime I had to resolve some problems with a ng2-dragula which is a lib I'm not happy with it. But today I noticed you have an other great lib ng2-dnd which I'm testing at the moment. Probably I can do the most thing I need with your lib, and your lib is more clear fully then others! =)

**Comment by akserg** [comment]
Hi Michael,

Thank you for warm words. Just bear in mind I published demo for latest version of ng2-toasty and ng2-dnd in another place: http://akserg.github.io/ng2-webpack-demo.

**Comment by mburger81** [comment]
@akserg okay thx, I will do it tomorrow, for today I have to do some other things.

do you think you can add also the functionality a drag&drop like switch positions for containers? Your lib does the wor for dragging into anything using html5 dragging function.

But I need also to drag DIVS (containert) for switching their positions.

I will share tomorrow your forked plnkt with my updates.
