### ISSUE TITLE
Add clearToast to service

### ISSUE THREAD

**Issue by sunilastudillo** [akserg/ng2-toasty#21]
Need a clear(id) method added to ToastyService. I know there is clearAll() method but I need to be able to clear a single toast from code.

Example:

I'm using a toastyService.wait() toast to display a wait message to the user. The relevant configuration for this toast is:
  toastOptions = {
    ...
    showClose: false,
    timeout: 0,
   ...
  }

This allows the toast to remain on the screen indefinitely. Now when certain conditions are met, I want to be able to remove that wait toast (and only that toast).

**Comment by akserg** [comment]
Added in 1.8.0
