### ISSUE TITLE
Build fails with Typescript 2.0

### ISSUE THREAD

**Issue by jppellerin** [akserg/ng2-toasty#23]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  This is a bug generated by webpack when typescript version is upgraded to 2.0.0.  Assuming that all future versions of typescript will have the same behaviour.
- **What is the current behavior?**
  On application build with webpack this is the error outputted : 

```
ERROR in ./~/ng2-toasty/ng2-toasty.ts
Module build failed: Error: Typescript emitted no output for /Users/jp/workspace/admin_angular2/node_modules/ng2-toasty/ng2-toasty.ts
    at Object.loader (/Users/jp/workspace/admin_angular2/node_modules/ts-loader/index.js:456:15)
```
- **Please tell us about your environment:**
- Angular version: 2.0.0-rc.4
- Webpack 1.13.1
- ts-loader 0.8.2
- ng2-toasty: 1.8.0

**Comment by akserg** [comment]
Hi @jppellerin 
Is that issue still exists?

**Comment by costis** [comment]
@jppellerin 
It exists for me

```
ERROR in ./~/ng2-toasty/ng2-toasty.ts
Module build failed: Error: Typescript emitted no output for /Users/costisp/projects/domains/node_modules/ng2-toasty/ng2-toasty.ts
    at Object.loader (/Users/costisp/projects/domains/node_modules/ts-loader/index.js:456:15)
 @ ./app/main.ts 6:19-51
```

```
tsc --version
Version 2.0.0
```

**Comment by jppellerin** [comment]
I get the same thing as @costis.

Also does not play well with Codelyzer (but that's a Codelyzer issue).  I had to deactivate to get the proper ng2-toasty error message.

**Comment by lbialy** [comment]
```
ERROR in /redacted/ui/src/tsconfig.json
error TS6059: File '/redacted/ui/node_modules/ng2-toasty/ng2-toasty.ts' is not under 'rootDir' '/redacted/ui/src'. 'rootDir' is expected to contain all source files.

ERROR in /redacted/ui/src/tsconfig.json
error TS6059: File '/redacted/ui/node_modules/ng2-toasty/src/toasty.component.ts' is not under 'rootDir' '/redacted/ui/src'. 'rootDir' is expected to contain all source files.

ERROR in /redacted/ui/src/tsconfig.json
error TS6059: File '/redacted/ui/node_modules/ng2-toasty/src/toasty.config.ts' is not under 'rootDir' '/redacted/ui/src'. 'rootDir' is expected to contain all source files.

ERROR in /redacted/ui/src/tsconfig.json
error TS6059: File '/redacted/ui/node_modules/ng2-toasty/src/toasty.container.ts' is not under 'rootDir' '/redacted/ui/src'. 'rootDir' is expected to contain all source files.

ERROR in /redacted/ui/src/tsconfig.json
error TS6059: File '/redacted/ui/node_modules/ng2-toasty/src/toasty.service.ts' is not under 'rootDir' '/redacted/ui/src'. 'rootDir' is expected to contain all source files.

ERROR in /redacted/ui/src/tsconfig.json
error TS6059: File '/redacted/ui/node_modules/ng2-toasty/src/toasty.utils.ts' is not under 'rootDir' '/redacted/ui/src'. 'rootDir' is expected to contain all source files.
```

Not sure if this is related to @jppellerin and @costis problem, but this is known problem of typescript described better [here](https://github.com/valor-software/ng2-select/issues/161) - basically having d.ts files in same directory as .ts files causes typescript to get confused and crash. I'm using Typescript 1.9.0.

**Comment by akserg** [comment]
I made changes in another library (https://github.com/akserg/ng2-slim-loading-bar), so now it's time to update this. one. I will let you know when you can test it.

**Comment by akserg** [comment]
Please use 2.0.0 release to confirm that issue is gone.

**Comment by jppellerin** [comment]
Finally circling back to this.  Confirmed working.
