### ISSUE TITLE
import {Toasty} from './src/toasty.container'; ^ ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by rtm** [akserg/ng2-toasty#24]
After installing ng2-toasty, a build gives me the following error:

```
/home/rtm/repos/triconinfotech/hitouch/node_modules/ng2-toasty/ng2-toasty.ts:7
import {Toasty} from './src/toasty.container';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

My tsconfig.json file is bare-bones, with neither files/filesGlob/excludes entries.

Do I need to do something with the gulpfile?
This is angular2 with ionic2 if that matters.

**Comment by NathofGod** [comment]
I'm having the same issue. Compiling with Browserify

`......./node_modules/ng2-toasty/ng2-toasty.ts:7
import {Toasty} from './src/toasty.container';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'`

**Comment by akserg** [comment]
I need to remove the source code from the build. Will do it tomorrow.
Thanks.

**Comment by akserg** [comment]
Please use 2.0.0 release to confirm that issue is gone.
