### ISSUE TITLE
WARNING export 'ToastData' was not found in './toasty.service'

### ISSUE THREAD

**Issue by Zambiorix** [akserg/ng2-toasty#25]
- **I'm submitting a ...**
  [x ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  a bug
- **What is the current behavior?**
  When serving, I get:
  WARNING in ./~/ng2-toasty/src/toasty.component.ts
  33:55 export 'ToastData' was not found in './toasty.service'

Toasts are not generated
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

I have created a new project via Angular-cli, the latest from master (with webpack) and then added toasty as per your guidelines.
- **What is the expected behavior?**
  That it works?
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
  "@angular/common": "2.0.0-rc.4",
  "@angular/compiler": "2.0.0-rc.4",
  "@angular/core": "2.0.0-rc.4",
  "@angular/forms": "0.2.0",
  "@angular/http": "2.0.0-rc.4",
  "@angular/platform-browser": "2.0.0-rc.4",
  "@angular/platform-browser-dynamic": "2.0.0-rc.4",
  "@angular/router": "3.0.0-beta.2",
  "angular2-localstorage": "^0.4.0",
  "core-js": "^2.4.0",
  "hammerjs": "^2.0.8",
  "ng2-bootstrap": "^1.0.24",
  "ng2-toasty": "^1.8.0",
  "reflect-metadata": "0.1.3",
  "rxjs": "5.0.0-beta.6",
  "ts-helpers": "^1.1.1",
  "zone.js": "0.6.12"
- Browser: all
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Zambiorix** [comment]
Update:

It works somewhat .. toasts are added to the screen, but they are just blank text .. css not working.

After timeout toast disappear, so I assume core functionality works, but visualisation not.

And then there is this WARNING still about missing export (ToastData).

**Comment by some1awesome** [comment]
I have the same problem.  I love using your toast services but I can't if it doesn't work with the new webpack angular cli. Thanks for all you do!

**Comment by akserg** [comment]
Please use 2.0.0 release to confirm that issue is gone.
