### ISSUE TITLE
Cannot read property 'next' of undefined

### ISSUE THREAD

**Issue by xianrui** [akserg/ng2-toasty#31]
TypeError: Cannot read property 'next' of undefined(…)
toasty.service.js:158 !!! Suggestion: Seems you forget add <ng2-toasty></ng2-toasty> into your html?

This code has a exception  in toasty.service.ts   page  

`// Push up a new toast item
    try {
      this.toastsSubscriber.next(toast);  //   **# has a exception** 
      // If we have a onAdd function, call it here
      if (toastyOptions.onAdd && isFunction(toastyOptions.onAdd)) {
        toastyOptions.onAdd.call(this, toast);
      }
    } catch (e) {
      console.log(e);
      console.log('!!! Suggestion: Seems you forget add <ng2-toasty></ng2-toasty> into your html?');
    }`

But I have added the code in the html page

excuse me  I should be?

**Comment by akserg** [comment]
Please use 2.0.0 release to confirm that issue is gone.

**Comment by akserg** [comment]
I'm closing this issue in respect to another [one](https://github.com/akserg/ng2-toasty/issues/39).

**Comment by sanket360** [comment]
I have downloaded 2.0.0 today still getting same error...

![1](https://cloud.githubusercontent.com/assets/16756121/18698436/d22c528c-7fe7-11e6-9080-e2981d962153.PNG)

[toasty.service.js.zip](https://github.com/akserg/ng2-toasty/files/484182/toasty.service.js.zip)
This is toasty.service.js file I get, after using `npm install ng2-toasty --save` command.
