### ISSUE TITLE
No ToastyModule exported

### ISSUE THREAD

**Issue by cschroeter** [akserg/ng2-toasty#32]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

Bug
- **What is the current behavior?**

ng2-toasty has no exported member 'ToastyModule'.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

ng new ng2-toasty
- **What is the expected behavior?**

There should be a ToastyModule
- **What is the motivation / use case for changing the behavior?**
- **Please tell us about your environment:**
- Angular version: 2.0.0-rc.6
- Browser: [all]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jasondana** [comment]
Just in case you aren't aware, the latest changes do contain a ToastyModule.  Unfortunately the build is failing and I suspect that is the reason a new version containing the changes is not being pushed to npm.

https://github.com/akserg/ng2-toasty/blob/master/index.ts#L36

**Comment by jaroslawziolkowski** [comment]
@akserg when latest version will available by npm? No I can download 1.10.1

**Comment by jvanhall** [comment]
Any idea on when this will be fixed, its preventing us from cutting over to RC7.  Thank you!

**Comment by akserg** [comment]
Please use 2.0.0 release to confirm that issue is gone.

**Comment by cschroeter** [comment]
@akserg works! 👍
