### ISSUE TITLE
Angular 2.0.0 compatibility

### ISSUE THREAD

**Issue by codyjdalton** [akserg/ng2-toasty#35]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

Feature
- **What is the current behavior?**

No worky
- **What is the motivation / use case for changing the behavior?**

Support Angular version 2.0.0
- **Please tell us about your environment:**
- Angular version: 2.0.0
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by cokearns** [comment]
Also experiencing issues with 2.0 and RC 6

**Comment by akserg** [comment]
Please use 2.0.0 release to confirm that issue is gone.

**Comment by clementbrunel** [comment]
Works for me :)
Thank you for the upgrade. 
The version is not pusblished in github release list, but available on npm.js.
