### ISSUE TITLE
Feature : Timeout independent toast + support for multiple line messages

### ISSUE THREAD

**Issue by uzumakinaruto123** [akserg/ng2-toasty#36]
- **I'm submitting a ...**
  [ ] bug report
  [ *] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**
  
    Feature to **prevent auto close** of the toast. That is making it timeout independent. which cant be closed until user clicks 'close' or its closed programmatically. 
  
    plus
  
    It would be great if we could change lines within error message.  escape character '\n' 
- **What is the current behavior?**
  
   Currently , to prevent auto close , we need to set very large timeout. like random 50000.  that can     be closed programmatically whenever needed.
- **What is the expected behavior?**
  If timeout is set to `0` , it should prevent close untill user clicks close/programmatically.
- **What is the motivation / use case for changing the behavior?**
  <br>
     Displaying validation errors in a toast. which should stay active until user notices/reads them. and  multiple validation errors on multiple lines.
  <br>
- **Please tell us about your environment:**
  <br>
- Angular version: 2.0.0-rc.4
- Browser: all 
  <br>

**Comment by akserg** [comment]
Set the timeout equals `0` or `null` to prevent autoclose in ToastOptions or ToastConfig:

```
var toastOptions:ToastOptions = {
            title: "My title",
            msg: "The message",
            showClose: true,
            timeout: null, // <!-- Here is your changes
            theme: 'default',
            onAdd: (toast:ToastData) => {
                console.log('Toast ' + toast.id + ' has been added!');
            },
            onRemove: function(toast:ToastData) {
                console.log('Toast ' + toast.id + ' has been removed!');
            }
        };
```
