### ISSUE TITLE
Can not import and use it with angular 2.0.0

### ISSUE THREAD

**Issue by tuoitrexuquang** [akserg/ng2-toasty#37]
I'm using angular 2 latest version and webpack. But i can't not import and use it
i follow document from https://github.com/akserg/ng2-toasty

I got error: Module '"../node_modules/ng2-toasty/index"' has no exported member 'ToastyModule'.
when import { ToastyModule } from 'ng2-toasty';

Could you pls help? thanks

**Comment by ranakrunal9** [comment]
You need to import from `ng2-toasty/ng2-toasty` like `import {ToastyModule} from 'ng2-toasty/ng2-toasty';`

**Comment by tuoitrexuquang** [comment]
Thanks, i work now

**Comment by Kekstas** [comment]
How you have fixed it I can't start it working with webpack and angular 2.0.0
when do 
import { ToastyModule } from 'ng2-toasty';  
it do not recognize  ng2-toasty as well as 
ToastyModule, ToastyService, ToastyConfig, ToastOptions, ToastData from 'ng2-toasty'
