### ISSUE TITLE
Delete confusing suggestion from source code

### ISSUE THREAD

**Issue by akserg** [akserg/ng2-toasty#39]
Remove `!!! Suggestion: Seems you forget add <ng2-toasty></ng2-toasty> into your html?'` frpm code because it confuses developers.

**Comment by sanket360** [comment]
I have downloaded 2.0.0 today still getting same error...

![1](https://cloud.githubusercontent.com/assets/16756121/18736542/9a251004-80a5-11e6-8bb2-6f783c52f1ee.PNG)
[toasty.service.js.zip](https://github.com/akserg/ng2-toasty/files/486465/toasty.service.js.zip)

This is toasty.service.js file I get, after using npm install ng2-toasty --save command.

**Comment by akserg** [comment]
Fixed in 2.0.1
