### ISSUE TITLE
How to disable timeout?

### ISSUE THREAD

**Issue by sanket360** [akserg/ng2-toasty#40]
How to disable timeout?

As per your config comment, you have mentioned set to false to disable. But which property I need to set to false?

```
 // How long (in miliseconds) the toasty shows before it's removed. Set to false to disable.
timeout: number = 5000;
```

Also, Is there a toasty message feature with user confirmation... like YES and NO buttons?

Environment:
Angular2 version 2.0.0
ng2-toasty version 2.0.1

**Comment by sanket360** [comment]
@akserg  Could you please respond on this?

**Comment by akserg** [comment]
Sorry, my bad. Please set it equals null/0 to turn off. 
I have updated the comment in the source code. 
Please close if all work as expected.

**Comment by sanket360** [comment]
Thanks... it working :+1:
