### ISSUE TITLE
How to set potition?

### ISSUE THREAD

**Issue by Redigast13** [akserg/ng2-toasty#44]
How to change position from default bottom-right to top-right. I tried  `this.toastyConfig.position = 'top-right';` but nothing was changed
- Angular version: 2.0.0

**Comment by akserg** [comment]
You can use the `position` property to customize the ng2-toasty component in your template. Default value is `bottom-right`. Possible values: `bottom-right`, `bottom-left`, `top-right`, `top-left`, `top-center`, `bottom-center`
Example: `<ng2-toasty [position]="'top-center'"></ng2-toasty>`
