### ISSUE TITLE
show toasty in center of screen

### ISSUE THREAD

**Issue by sanket360** [akserg/ng2-toasty#45]
In ng2-toasty, I can see these options-
bottom-right, bottom-left, top-right, top-left, top-center, bottom-center

How do I show toasty message center of screen?

My use-case is, I want to show one toasty message center of screen. limit property allow me show only one message. But position property have above mentioned options.

Environment:
Angular2 version 2.0.0
ng2-toasty version 2.0.1

**Comment by akserg** [comment]
I added the new option `center-center` and published version 2.1.0. Can you check does it work for you?

**Comment by sanket360** [comment]
Thanks @akserg for quick response :+1:
