### ISSUE TITLE
Cannot read property 'getOptional' of undefined

### ISSUE THREAD

**Issue by ghost** [akserg/ng2-toasty#5]
I'm trying to implement ng2-toasty in a project i'm working on, but as soon as I add ToastyServices or ToastyConfig to the bootstrap, there is an error thrown. I am compiling to ES5, using ng2-bootstrap 1.0.7 and using angular2 beta9. I also tried following the tutorial step by step but as soon as I get too the bootstrap part, it gives me the same issue. Have you run into anything like this?

**Comment by akserg** [comment]
May I see console log of you app?

**Comment by akserg** [comment]
Any feedback about this issue? Does it still exist?
