### ISSUE TITLE
[2.2.0] Can't bind to 'ngClass' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by chunghha** [akserg/ng2-toasty#54]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
A bug report with the 2.2.0 just updated. These errors didn't occur with the 2.1.0. 

* **What is the current behavior?**
These errors are displayed: (not whole but part of the errors.)

```
Can't bind to 'ngClass' since it isn't a known property of 'div'. ("
        <div class="toast" [ERROR ->][ngClass]="[toast.type, toast.theme]">
            <div *ngIf="toast.showClose" class="close-button" "): ToastComponent@1:27
Can't bind to 'ngIf' since it isn't a known property of 'div'. ("
        <div class="toast" [ngClass]="[toast.type, toast.theme]">
            <div [ERROR ->]*ngIf="toast.showClose" class="close-button" (click)="close($event)"></div>
            <div *ngIf="t"): ToastComponent@2:17
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
        <div class="toast" [ngClass]="[toast.type, toast.theme]">
            [ERROR ->]<div *ngIf="toast.showClose" class="close-button" (click)="close($event)"></div>
            <div *ng"): ToastComponent@2:12

```

I believe taking out CommonModule from index.ts by this commit causes the errors.
https://github.com/akserg/ng2-toasty/commit/7d7c0a837991f5bf7e2e448944d9e285d20725f1

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

* **What is the expected behavior?**
No error should be displayed to console.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

 Angular version: 2.4.1
 Angular CLI: 1.0.0-beta.24
 ng2-toasty: 2.2.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by akserg** [comment]
I have the same issue - fixing.

**Comment by akserg** [comment]
Fixed in 2.2.1 
Please confirm.

**Comment by chunghha** [comment]
It got fixed. Thanks a lot!

**Comment by akserg** [comment]
I'm still busy testing the latest build, so please, if you find other issues - let me know.
