### ISSUE TITLE
Need to manually put ToastyConfig in providers section

### ISSUE THREAD

**Issue by deeg** [akserg/ng2-toasty#55]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

If you do not put ToastyConfig into providers it throws an error:

`EXCEPTION: No provider for ToastyConfig!`

* **What is the expected behavior?**

I should not have to put ToastyConfig into my providers section

- Angular version: 2.4.1

**Comment by akserg** [comment]
Just fixed now in 2.2.2
Please check.

**Comment by chunghha** [comment]
For me, it's fixed.

**Comment by deeg** [comment]
Indeed working now. Thanks for the quick turnaround.

**Comment by akserg** [comment]
Thank you all.
