### ISSUE TITLE
[2.2.1] Please update README about providers.

### ISSUE THREAD

**Issue by chunghha** [akserg/ng2-toasty#56]
* **I'm submitting a ...**
[ ] bug report
[*] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Just for document update request.

* **What is the current behavior?**
From 2.2.1, user's module that imports ToastyModule also needs to set providers by 

`providers: [ToastyService, ToastyConfig]`

so please update the readme. If not set, error is displayed to console like this

` No provider for ToastyConfig!`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

Angular version: 2.4.1
Angular CLI: beta. 24
ng2-toasty: 2.2.1

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by chunghha** [comment]
Close. Dup of #55

**Comment by akserg** [comment]
Thanks.
