### ISSUE TITLE
Update for Angular > 2

### ISSUE THREAD

**Issue by PhilippSoehnlein** [akserg/ng2-toasty#75]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Using Angular 4 and ng2-toasty in one application will produce a warning by `npm install`, because ng2-toasty defines only Angular 2.4 as Peer-Depedency.

**Comment by akserg** [comment]
Hi @PhilippSoehnlein 

I have published the release 4.0.0 on npmjs.com. Please let me know does it work for you?

**Comment by PhilippSoehnlein** [comment]
Hi @akserg,

yes, looks good in our application. Thanks!
