### ISSUE TITLE
Custom Icon (with Material icons)

### ISSUE THREAD

**Issue by rscottfree** [akserg/ng2-toasty#76]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Icons are unchangeable

* **What is the expected behavior?**
Define a custom icon or HTML to use in the icon spot

* **What is the motivation / use case for changing the behavior?**
I'd like to use a material design icon instead of the icons provided.

This would be nice if it worked just like custom HTML in the title and message.
If that doesn't work out, at minimum it would be nice to specify a material design icon name.

**Comment by EnigmaticCode** [comment]
All of the icons displayed are css backgrounds.  Using a combination of the toasty-type-* and toasty-theme-* css classes you should be able to customize this.

**Comment by rscottfree** [comment]
Thanks for the info. The problem I was having is showing font icons in only CSS, but I learned it is possible. As stated, we can use those toasty-* classes to customize it without needing HTML, and I can use font icons directly in CSS.

Links that helped me:
http://stackoverflow.com/questions/14736496/use-font-awesome-icons-in-css
https://css-tricks.com/html-for-icon-font-usage/
http://chipcullen.com/using-icons-from-icon-fonts-directly-in-css/
