### ISSUE TITLE
Styles don't work

### ISSUE THREAD

**Issue by asterieks** [akserg/ng2-toasty#80]
Hi
I was trying to apply ng2-toasty for my application.
 - angular 4.0.3
 - ng2-toasty 4.0.0
 - webpack  2.5.1
 - typescript 2.3.2
 - Google Chrome
 - whithot angular-cli (I build bundle.js with webpack manually and then copy to tomcat).

Link see further.
 
Following installation steps I met issue with styles.
Actually toasts appeared but without any styles.
In another words I was able to change time duration, message and type of toast.
But no color and no alignment, no position and no background images. This properties didn't work. 

I suppose that style was not included in bundle script.

Finnaly I resolved such issue in below way:
1) manually added  line of code to toast.component.js  : 
            ToastComponent.decorators = [ Component, args: [{
                    selector: 'ng2-toast',
                    template: "...............................",
                    **styles:[ require('../style-bootstrap-toast.css')]** //my customisation
            },] }, ];
2) manually added  piece of code to toasty.component.js:
            ToastyComponent.decorators = [ { type: Component, args: [{
                    selector: 'ng2-toasty',
                    template: "............................",
                    **styles:[ require('../style-bootstrap-toasty.css')]** //my customisation
            },] },];                  
 3) Divided bootstrap style into two part for #toasty and #toast respectively.
Details you can find here:
https://github.com/asterieks/Reportum/commit/243de57ba5161e44077dff2eabfdcad3ac9e2075

After such refactoring style appeared in bundle script and was applyed for components.
Such solution is weird. 
Could you help me apply ng2-toasty in a correct way.

**Comment by akserg** [comment]
Hi @asterieks,

You are right - bundle does not (and should not) include the styles. There are several reasons to prevent it if you are following the separation of concerns principles in your development. 
I don't know what the build pipeline do you have. I covered two of many possible ways of how to include the styles in referenced projects (look at examples mentioned in README file). 

> without angular-cli (I build bundle.js with webpack manually and then copy to tomcat).

I don't understand your point do not use `angular-cli` in that case. You can build your project with the help of Angular CLI and copy resulting artefacts into tomcat automatically (Check the following [post ](http://stackoverflow.com/questions/41109436/angular-cli-run-command-after-ng-build) on StackOverflow). 

If that doesn't work for you - find the way to copy one of [style files](https://github.com/akserg/ng2-toasty#1-update-the-markup) into tomcat as described in README.

Let me know if that post helps you.

**Comment by asterieks** [comment]
Hi Sergey

thanks for responce.

I will try.

asterieks

**Comment by akserg** [comment]
I use SpringBoot at the back end st work as well. Let me know if you need anything else.

**Comment by klanglie** [comment]
Forgive me, I am a noob. I use webpack without angular-cli. Your demo does not include a wepack.config.js file. So I cannot figure out how to configure it so that it includes the style sheets. I don't know what SpringBoot or tomcat are. I am developing on Windows using VS Code and am using the following starter project for my work: https://github.com/angularclass/angular-starter

**Comment by kentryan** [comment]
https://cdn.jsdelivr.net/npm/ng2-toasty@4.0.3/style.css
try to import this to your project file

**Comment by asterieks** [comment]
@kentryan 
Thanks a lot. It works in way u recommended.
My example is here https://github.com/asterieks/Reportum/commit/1781871dbb64b2fb9040add5011d05504f35c55f

**Comment by PalindiB** [comment]
@kentryan @asterieks Can I know where to import https://cdn.jsdelivr.net/npm/ng2-toasty@4.0.3/style.css in my project, please?
